# Scene Identifier
scene.id=payment

# Paths
scene.fxml=/scenes/payment/payment_scene.fxml
scene.css.light=/scenes/payment/payment_style_light.css
scene.css.dark=/scenes/payment/payment_style_dark.css
scene.messages=scenes/payment/messages_payment_hu

# Controller and Title
scene.controller=cash_flow.controller.
scene.title=

# Size
scene.size.width=
scene.size.height=
scene.resizable=true

# Additional UI behavior
scene.transition=fade
scene.placement=
