# Scene Identifier
scene.id=split_center

# Paths
scene.fxml=/scenes/split_center/split_center_scene.fxml
scene.css.light=/scenes/split_center/split_center_style_light.css
scene.css.dark=/scenes/split_center/split_center_style_dark.css
scene.messages=scenes/split_center/messages_split_center_hu

# Controller and Title
scene.controller=cash_flow.controller.SplitCenterController
scene.title=

# Size
scene.size.width=1280
scene.size.height=800
scene.resizable=true

# Additional UI behavior
scene.transition=fade
scene.placement=center
scene.side=
