# Scene Identifier
scene.id=user_logs

# Paths
scene.fxml=/scenes/user_logs/user_logs_scene.fxml
scene.css.light=/scenes/user_logs/user_logs_style_light.css
scene.css.dark=/scenes/user_logs/user_logs_style_dark.css
scene.messages=scenes/user_logs/messages_user_logs_hu

# Controller and Title
scene.controller=cash_flow.controller.
scene.title=

# Size
scene.size.width=
scene.size.height=
scene.resizable=true

# Additional UI behavior
scene.transition=fade
scene.placement=
