# Scene Identifier
scene.id=member_overview

# Paths
scene.fxml=/scenes/member_overview/member_overview_scene.fxml
scene.css.light=/scenes/member_overview/member_overview_style_light.css
scene.css.dark=/scenes/member_overview/member_overview_style_dark.css
scene.messages=scenes/member_overview/messages_member_overview_hu

# Controller and Title
scene.controller=cash_flow.controller.
scene.title=member_overview.title

# Size
scene.size.width=800
scene.size.height=600
scene.resizable=true

# Additional UI behavior
scene.transition=fade
scene.placement=right
