# Scene Identifier
scene.id=base

# Paths
scene.fxml=/scenes/add_group_members/add_members_scene.fxml
scene.css.light=/scenes/add_group_members/add_members_style_light.css
scene.css.dark=/scenes/add_group_members/add_members_style_dark.css
scene.messages=scenes/add_group_members/messages_add_members_hu

# Controller and Title
scene.controller=cash_flow.controller.AddGroupMembersController
scene.title=Tagok hozzáadása a csoporthoz

# Size
scene.size.width=1280
scene.size.height=800
scene.resizable=true

# Additional UI behavior
scene.transition=fade
scene.placement=base
