package cash_flow.domain;

import lombok.Getter;

@Getter
public enum PaymentEventType {
    PAYMENT_MADE,
    PAYMENT_UPDATED,
    PAYMENT_DELETED,
    PAYMENT_REFUNDED,
    REMAINING_BALANCE_REFUNDED,
    REMAINING_GROUP_BALANCE_REDIRECTED,
    OUTGOING_PAYMENT_CREATED,
    OUTGOING_PAYMENT_UPDATED,
    OUTGOING_PAYMENT_DELETED
}
