# Scene Identifier
scene.id=group_overview

# Paths
scene.fxml=/scenes/group_overview/group_overview_scene.fxml
scene.css.light=/scenes/group_overview/group_overview_style_light.css
scene.css.dark=/scenes/group_overview/group_overview_style_dark.css
scene.messages=scenes/group_overview/messages_group_overview_hu

# Controller and Title
scene.controller=cash_flow.controller.
scene.title=group_overview.title

# Size
scene.size.width=100
scene.size.height=100
scene.resizable=true

# Additional UI behavior
scene.transition=fade
scene.placement=
