# Scene Identifier
scene.id=

# Paths
scene.fxml=/scenes/group_data/group_data_scene.fxml
scene.css.light=/scenes/group_data/group_data_style_light.css
scene.css.dark=/scenes/group_data/group_data_style_dark.css
scene.messages=scenes/group_data/messages_group_data_hu

# Controller and Title
scene.controller=cash_flow.controller.GroupDataController
scene.title=

# Size
scene.size.width=
scene.size.height=
scene.resizable=true

# Additional UI behavior
scene.transition=fade
scene.placement=
