# Scene Identifier
scene.id=list_cell

# Paths
scene.fxml=/scenes/list_cell/list_cell_scene.fxml
scene.css.light=/scenes/list_cell/list_cell_style_light.css
scene.css.dark=/scenes/list_cell/list_cell_style_dark.css
scene.messages=scenes/list_cell/messages_list_cell_hu

# Controller and Title
scene.controller=cash_flow.controller.ChooseCashCollectionGroupController
scene.title=Listázandó csoportok

# Size
scene.size.width=234
scene.size.height=372
scene.resizable=true

# Additional UI behavior
scene.transition=fade
scene.placement=component
