# Scene Identifier
scene.id=required_payment

# Paths
scene.fxml=/scenes/required_payment/required_payment_scene.fxml
scene.css.light=/scenes/required_payment/required_payment_style_light.css
scene.css.dark=/scenes/required_payment/required_payment_style_dark.css
scene.messages=scenes/required_payment/messages_required_payment_hu

# Controller and Title
scene.controller=cash_flow.controller.
scene.title=Required Payment

# Size
scene.size.width=100
scene.size.height=100
scene.resizable=true

# Additional UI behavior
scene.transition=fade
scene.placement=extra
