# Scene Identifier
scene.id=base

# Paths
scene.fxml=/scenes/add_group_overseer/add_group_overseer_scene.fxml
scene.css.light=/scenes/add_group_overseer/add_group_overseer_style_light.css
scene.css.dark=/scenes/add_group_overseer/add_group_overseer_style_dark.css
scene.messages=scenes/add_group_overseer/messages_add_group_overseer_hu

# Controller and Title
scene.controller=cash_flow.controller.AddGroupMembersController
scene.title=Tagok hozzáadása a csoporthoz

# Size
scene.size.width=300
scene.size.height=300
scene.resizable=true

# Additional UI behavior
scene.transition=fade
scene.placement=extra
scene.side=
