# Scene Identifier
scene.id=member_exemptions

# Paths
scene.fxml=/scenes/member_exemptions/member_exemptions_scene.fxml
scene.css.light=/scenes/member_exemptions/member_exemptions_style_light.css
scene.css.dark=/scenes/member_exemptions/member_exemptions_style_dark.css
scene.messages=scenes/member_exemptions/messages_member_exemptions_hu

# Controller and Title
scene.controller=cash_flow.controller.
scene.title=

# Size
scene.size.width=
scene.size.height=
scene.resizable=true

# Additional UI behavior
scene.transition=fade
scene.placement=
