# Scene Identifier
scene.id=base

# Paths
scene.fxml=/scenes/base/base_layout_scene.fxml
scene.css.light=/scenes/base/base_style_light.css
scene.css.dark=/scenes/base/base_style_dark.css
scene.messages=scenes/base/messages_base_hu

# Controller and Title
scene.controller=cash_flow.controller.BaseLayoutController
scene.title=Osztálypénz kezel?

# Size
scene.size.width=1280
scene.size.height=800
scene.resizable=true

# Additional UI behavior
scene.transition=fade
scene.placement=base
