choose_cash_collection_group_scene=/fxml/choose_cash_collection_group_scene.fxml=extra
list_cell_scene=/fxml/list_cell.fxml=component
base_layout_scene=/fxml/base_layout_scene.fxml=base
loading_scene=/fxml/loading_scene.fxml=center