# Scene Identifier
scene.id=

# Paths
scene.fxml=/scenes/member_data/member_data_scene.fxml
scene.css.light=/scenes/member_data/member_data_style_light.css
scene.css.dark=/scenes/member_data/member_data_style_dark.css
scene.messages=scenes/member_data/messages_member_data_hu

# Controller and Title
scene.controller=cash_flow.controller.MemberDataController
scene.title=

# Size
scene.size.width=400
scene.size.height=600
scene.resizable=true

# Additional UI behavior
scene.transition=fade
scene.placement=split_center
scene.side=right
