# Scene Identifier
scene.id=loading

# Paths
scene.fxml=/scenes/loading/loading_scene.fxml
scene.css.light=/scenes/loading/loading_style_light.css
scene.css.dark=/scenes/loading/loading_style_dark.css
scene.messages=scenes/loading/messages_loading_hu

# Controller and Title
scene.controller=cash_flow.controller.LoadingController
scene.title=Betöltés

# Size
scene.size.width=200
scene.size.height=200
scene.resizable=true

# Additional UI behavior
scene.transition=fade
scene.placement=center
