CREATE TABLE payments
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount          DOUBLE PRECISION                        NOT NULL,
    payment_date    TIMESTAMP                               NOT NULL,
    group_member_id VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_payments PRIMARY KEY (id)
);

ALTER TABLE payments
    ADD CONSTRAINT FK_PAYMENTS_ON_GROUP_MEMBER FOREIGN KEY (group_member_id) REFERENCES group_members (id);