CREATE TABLE required_payments
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount          DOUBLE PRECISION                        NOT NULL,
    created_date    TIMESTAMP                               NOT NULL,
    due_date        TIMESTAMP,
    is_paid         BOOLEAN                                 NOT NULL,
    group_member_id VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_required_payments PRIMARY KEY (id)
);

ALTER TABLE required_payments
    ADD CONSTRAINT FK_REQUIRED_PAYMENTS_ON_GROUP_MEMBER FOREIGN KEY (group_member_id) REFERENCES group_members (id);