CREATE TABLE group_currency_history
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date          TIMESTAMP                               NOT NULL,
    group_id      BIGINT                                  NOT NULL,
    logs_id       BIGINT                                  NOT NULL,
    currency_code VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_group_currency_history PRIMARY KEY (id)
);

ALTER TABLE group_currency_history
    ADD CONSTRAINT uc_group_currency_history_logs UNIQUE (logs_id);

ALTER TABLE group_currency_history
    ADD CONSTRAINT FK_GROUP_CURRENCY_HISTORY_ON_CURRENCY_CODE FOREIGN KEY (currency_code) REFERENCES currency (code);

ALTER TABLE group_currency_history
    ADD CONSTRAINT FK_GROUP_CURRENCY_HISTORY_ON_GROUP FOREIGN KEY (group_id) REFERENCES groups (id);

ALTER TABLE group_currency_history
    ADD CONSTRAINT FK_GROUP_CURRENCY_HISTORY_ON_LOGS FOREIGN KEY (logs_id) REFERENCES logs (id);
