# Scene Identifier
scene.id=choose_cash_collection_group

# Paths
scene.fxml=/scenes/group_choosing/choose_cash_collection_group_scene.fxml
scene.css.light=/scenes/group_choosing/choose_cash_collection_group_style_light.css
scene.css.dark=/scenes/group_choosing/choose_cash_collection_group_style_dark.css
scene.messages=scenes/group_choosing/messages_choose_cash_collection_group_hu

# Controller and Title
scene.controller=cash_flow.controller.ChooseCashCollectionGroupController
scene.title=P�nzgy�jt�s csoport v�laszt�s

# Size
scene.size.width=234
scene.size.height=372
scene.resizable=true

# Additional UI behavior
scene.transition=fade
scene.placement=extra
scene.side=
